/**
 * dom/hash.js
 */

var hashedObjectCache = {};

/**
 * @const
 */
var HEXCHARS = '0123456789ABCDEF';

/**
 * getHashId
 *
 * Get hash ID for an object, converting the object to a model with the original
 * object as its contents if necessary.  The hash is stored in hashedObjectCache
 * so that object can be retrieved after parsing the HTML generated by the template.
 */
function getHashId(obj) {
    if (!isQueryable(obj)) {
        var instaModel = tbone['make']();
        instaModel['query']('', obj);
        obj = instaModel;
    }
    if (!obj.hashId) {
        var hashArray = [];
        for (var i = 20; i; i--) {
            hashArray.push(HEXCHARS.charAt(Math.floor(Math.random() * HEXCHARS.length)));
        }
        obj.hashId = hashArray.join('');
    }
    hashedObjectCache[obj.hashId] = obj;
    return obj.hashId;
}
